#!/bin/bash
#
# Download and unpack the packages referenced in 'SOURCES.txt' under
# directory 'src'.
#

if [ ! -d src ]
then
    mkdir src
fi

1>&2 echo "Download"

cd src

if $(2>&1 1>/dev/null which wget)
then
    #
    # Download sources, once, continue partials
    #
    if wget -c -nc -i ../SOURCES.txt
    then
	1>&2 echo "OK"
    else
	1>&2 echo "$0 error downloading files referenced from SOURCES.txt."
	exit 1
    fi
else
    cat<<EOF>&2
$0 error, missing 'wget' required for downloading source packages.
EOF
    exit 1
fi

1>&2 echo "Unpack"

for pkg in *.tar*
do

    case $(file ${pkg}) in

	*compressed*)

	    if tar xfz ${pkg}
	    then
		echo "U ${pkg}"
	    else
		echo "X ${pkg}"
	    fi
	    ;;
	*)
	    if tar xf ${pkg}
	    then
		echo "U ${pkg}"
	    else
		echo "X ${pkg}"
	    fi
	    ;;
    esac
done


exit 0
