#!/bin/bash
#
# Download sample fits files from SOURCES.txt to directory 'samples'
#

if [ ! -d samples ]
then
  mkdir samples
fi

if cd samples
then
    for url in $(cat ../SAMPLES.txt)
    do
	#
	# N.B. 
	#  Need [loop (get, clean) ] over httpd index files!
	#
	wget -nd -np -nc -r -c ${url}

	rm -f $(ls *.html*)

    done

    exit 0
else 
  cat<<EOF>&2
$0 error changing directory to 'samples'.
EOF
  exit 1
fi
